<a href="https://colab.research.google.com/github/vijayalakshmig226/Python-Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,2,3,4])  #list
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a = np.array((1,2,3,4))  #tuple
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a = np.array(100)  #0Dimension
print(a)
print("Dimension : ", a.ndim)

100
Dimension :  0


In [ ]:
import numpy as np
a = np.array([100,200,300])  #1Dimension
print(a)
print("Dimension : ", a.ndim)

[100 200 300]
Dimension :  1


In [ ]:
import numpy as np
a = np.array([[100,200,300], [400,500,600]])  #2Dimension
print(a)
print("Dimension : ", a.ndim)

[[100 200 300]
 [400 500 600]]
Dimension :  2


In [ ]:
import numpy as np
a = np.array([[[100,200,300], [400,500,600]],[[100,200,300], [400,500,600]]])  #3Dimension
print(a)
print("Dimension : ", a.ndim)

[[[100 200 300]
  [400 500 600]]

 [[100 200 300]
  [400 500 600]]]
Dimension :  3


In [ ]:
import numpy as np
a = np.zeros([2,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
a = np.arange(0 ,20, 3)
print(a)

[ 0  3  6  9 12 15 18]


In [1]:
import numpy as np    #slicing
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[1:5])

[1 2 3 4]


In [2]:
import numpy as np    #slicing
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[:5])

[0 1 2 3 4]


In [3]:
import numpy as np    #slicing
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[4:])

[4 5 6 7 8 9]


In [4]:
import numpy as np    #slicing
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[-3:-1])

[7 8]


In [11]:
import numpy as np    #slicing
a = np.array([[100,200,300,400,500,600,700], [300,400,500,600,700,800,900]])  #2Dimension
print(a[0, 2:5])

[300 400 500]


In [13]:
import numpy as np    # type conversion float to int
a = np.array([1.1,2.1,3.1])
print(a.astype('i'))

[1 2 3]


In [14]:
import numpy as np    # type conversion int to boolean
a = np.array([1,0])
print(a.astype('bool'))

[ True False]


In [21]:
import numpy as np
a = np.array([1,2,3,4])     # copy
b = a.copy()
print(a)
print(b)

a[1] = 20
b[2] = 30
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]
[ 1 20  3  4]
[ 1  2 30  4]


In [22]:
import numpy as np
a = np.array([1,2,3,4])     # view
b = a.view()
print(a)
print(b)

a[1] = 20
print(a)
print(b)

b[1] = 10
print(a)
print(b)

[1 2 3 4]
[1 2 3 4]
[ 1 20  3  4]
[ 1 20  3  4]
[ 1 10  3  4]
[ 1 10  3  4]


In [23]:
import numpy as np
a = np.array([[100,200,300], [400,500,600]])  # shape
print(a.shape)

(2, 3)


In [24]:
import numpy as np      # convert 1D array into 2D array
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [25]:
import numpy as np      # convert 1D array into 3D array
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [27]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
print(a.reshape(2,2,-1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
import numpy as np
a = np.array([[100,200,300], [400,500,600]])  #Multi Dimension into 1D
print(a.reshape(-1))

[100 200 300 400 500 600]
