<a href="https://colab.research.google.com/github/vijayalakshmig226/Python-Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,2,3,4])  #list
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a = np.array((1,2,3,4))  #tuple
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a = np.array(100)  #0Dimension
print(a)
print("Dimension : ", a.ndim)

100
Dimension :  0


In [ ]:
import numpy as np
a = np.array([100,200,300])  #1Dimension
print(a)
print("Dimension : ", a.ndim)

[100 200 300]
Dimension :  1


In [ ]:
import numpy as np
a = np.array([[100,200,300], [400,500,600]])  #2Dimension
print(a)
print("Dimension : ", a.ndim)

[[100 200 300]
 [400 500 600]]
Dimension :  2


In [ ]:
import numpy as np
a = np.array([[[100,200,300], [400,500,600]],[[100,200,300], [400,500,600]]])  #3Dimension
print(a)
print("Dimension : ", a.ndim)

[[[100 200 300]
  [400 500 600]]

 [[100 200 300]
  [400 500 600]]]
Dimension :  3


In [ ]:
import numpy as np
a = np.zeros([2,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
a = np.arange(0 ,20, 3)
print(a)

[ 0  3  6  9 12 15 18]


In [1]:
import numpy as np    #slicing
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[1:5])

[1 2 3 4]


In [2]:
import numpy as np    #slicing
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[:5])

[0 1 2 3 4]


In [3]:
import numpy as np    #slicing
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[4:])

[4 5 6 7 8 9]


In [4]:
import numpy as np    #slicing
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(a[-3:-1])

[7 8]


In [11]:
import numpy as np    #slicing
a = np.array([[100,200,300,400,500,600,700], [300,400,500,600,700,800,900]])  #2Dimension
print(a[0, 2:5])

[300 400 500]
