<a href="https://colab.research.google.com/github/vijayalakshmig226/Python-Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.array([1,2,3,4])  #list
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
a = np.array((1,2,3,4))  #tuple
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
a = np.array(100)  #0Dimension
print(a)
print("Dimension : ", a.ndim)

100
Dimension :  0


In [6]:
import numpy as np
a = np.array([100,200,300])  #1Dimension
print(a)
print("Dimension : ", a.ndim)

[100 200 300]
Dimension :  1


In [8]:
import numpy as np
a = np.array([[100,200,300], [400,500,600]])  #2Dimension
print(a)
print("Dimension : ", a.ndim)

[[100 200 300]
 [400 500 600]]
Dimension :  2
